package com.tianwen.news.data.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table AUTO_REPORT.
 */
public class AutoReport {

    private Long id;
    private String stockName;
    private String stockCode;
    /** Not-null value. */
    private String fileName;
    private Long date;

    public AutoReport() {
    }

    public AutoReport(Long id) {
        this.id = id;
    }

    public AutoReport(Long id, String stockName, String stockCode, String fileName, Long date) {
        this.id = id;
        this.stockName = stockName;
        this.stockCode = stockCode;
        this.fileName = fileName;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStockName() {
        return stockName;
    }

    public void setStockName(String stockName) {
        this.stockName = stockName;
    }

    public String getStockCode() {
        return stockCode;
    }

    public void setStockCode(String stockCode) {
        this.stockCode = stockCode;
    }

    /** Not-null value. */
    public String getFileName() {
        return fileName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

}
