package com.tianwen.news.data.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.tianwen.news.data.db.NewsTypeDao;
import com.tianwen.news.data.db.StockDao;
import com.tianwen.news.data.db.SearchHistoryDao;
import com.tianwen.news.data.db.ReadDao;
import com.tianwen.news.data.db.AutoReportDao;
import com.tianwen.news.data.db.MessagesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 3): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        NewsTypeDao.createTable(db, ifNotExists);
        StockDao.createTable(db, ifNotExists);
        SearchHistoryDao.createTable(db, ifNotExists);
        ReadDao.createTable(db, ifNotExists);
        AutoReportDao.createTable(db, ifNotExists);
        MessagesDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        NewsTypeDao.dropTable(db, ifExists);
        StockDao.dropTable(db, ifExists);
        SearchHistoryDao.dropTable(db, ifExists);
        ReadDao.dropTable(db, ifExists);
        AutoReportDao.dropTable(db, ifExists);
        MessagesDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(NewsTypeDao.class);
        registerDaoClass(StockDao.class);
        registerDaoClass(SearchHistoryDao.class);
        registerDaoClass(ReadDao.class);
        registerDaoClass(AutoReportDao.class);
        registerDaoClass(MessagesDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
