package com.tianwen.news.data.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGES.
 */
public class Messages {

    /** Not-null value. */
    private String id;
    private String fromAccount;
    private String fromName;
    private String content;
    private Long date;
    private Integer autoShow;
    private Integer type;

    public Messages() {
    }

    public Messages(String id) {
        this.id = id;
    }

    public Messages(String id, String fromAccount, String fromName, String content, Long date, Integer autoShow, Integer type) {
        this.id = id;
        this.fromAccount = fromAccount;
        this.fromName = fromName;
        this.content = content;
        this.date = date;
        this.autoShow = autoShow;
        this.type = type;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getFromAccount() {
        return fromAccount;
    }

    public void setFromAccount(String fromAccount) {
        this.fromAccount = fromAccount;
    }

    public String getFromName() {
        return fromName;
    }

    public void setFromName(String fromName) {
        this.fromName = fromName;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public Integer getAutoShow() {
        return autoShow;
    }

    public void setAutoShow(Integer autoShow) {
        this.autoShow = autoShow;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
