package com.tianwen.news.data.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table READ.
 */
public class Read {

    /** Not-null value. */
    private String newsId;
    private Long date;

    public Read() {
    }

    public Read(String newsId) {
        this.newsId = newsId;
    }

    public Read(String newsId, Long date) {
        this.newsId = newsId;
        this.date = date;
    }

    /** Not-null value. */
    public String getNewsId() {
        return newsId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNewsId(String newsId) {
        this.newsId = newsId;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

}
